# Generated by Django 4.1.7 on 2023-03-12 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_item_status'),
        ('layaway_plans', '0003_layawayplan_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='layawayplan',
            name='items',
            field=models.ManyToManyField(to='items.item'),
        ),
    ]
