# Generated by Django 4.2rc1 on 2023-03-23 20:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_balance'),
        ('drawers', '0003_drawer_closed_by_alter_drawer_opened_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawer',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='stores.store'),
        ),
    ]
