# Generated by Django 4.1.7 on 2023-03-11 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0004_alter_customer_state'),
        ('transactions', '0004_transaction_transaction_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='PawnLoan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principle_amount', models.DecimalField(decimal_places=2, max_digits=9)),
                ('amount_due', models.DecimalField(decimal_places=2, max_digits=9)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('transactions', models.ManyToManyField(to='transactions.transaction')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
