# Generated by Django 4.1.7 on 2023-03-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pawn_loans', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pawnloan',
            name='date_due',
            field=models.DateField(blank=True, null=True),
        ),
    ]
