# Generated by Django 4.2b1 on 2023-03-04 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=24)),
                ('middle_name', models.CharField(blank=True, max_length=24, null=True)),
                ('last_name', models.CharField(max_length=24)),
                ('address_1', models.CharField(max_length=48)),
                ('address_2', models.CharField(blank=True, max_length=48, null=True)),
                ('phone_number', models.CharField(blank=True, max_length=9, null=True)),
            ],
        ),
    ]
