# Generated by Django 4.2b1 on 2023-03-04 01:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_alter_customer_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(default='Tinpoint', max_length=32),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('ky', 'Kentucky')], default='ky', max_length=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='zip_code',
            field=models.CharField(default='12345', max_length=5),
            preserve_default=False,
        ),
    ]
