# Generated by Django 4.2b1 on 2023-03-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='make',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='model',
            field=models.CharField(blank=True, max_length=48, null=True),
        ),
    ]
