# Generated by Django 4.1.7 on 2023-03-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_item_price_item_price_in_item_price_out'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('saleable', 'Saleable'), ('sold', 'Sold'), ('hold', 'Hold'), ('police_hold', 'Police Hold')], max_length=11),
        ),
    ]
