# Generated by Django 4.1.7 on 2023-03-11 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('pawn', 'Pawn'), ('saleable', 'Saleable'), ('sold', 'Sold'), ('hold', 'Hold'), ('police_hold', 'Police Hold')], max_length=11),
        ),
    ]
