# Generated by Django 4.1.7 on 2023-03-15 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0007_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('pawn', 'Pawn'), ('redeem', 'Redeemed'), ('saleable', 'Saleable'), ('sold', 'Sold'), ('hold', 'Hold'), ('police_hold', 'Police Hold')], max_length=11),
        ),
    ]
