# Generated by Django 4.1.7 on 2023-03-16 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_squashed_0008_alter_item_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price_in',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
