# Generated by Django 4.1.7 on 2023-03-16 21:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0009_alter_item_price_in'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_start', models.DateTimeField(auto_now_add=True)),
                ('time_end', models.DateTimeField(blank=True, null=True)),
                ('items', models.ManyToManyField(related_name='all_inventory', to='items.item')),
                ('items_left', models.ManyToManyField(related_name='inventory_left', to='items.item')),
            ],
        ),
    ]
