# Generated by Django 4.1.7 on 2023-03-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0011_alter_inventoryaudit_items_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventoryaudit',
            name='items',
            field=models.ManyToManyField(blank=True, related_name='all_inventory', to='items.item'),
        ),
        migrations.AlterField(
            model_name='inventoryaudit',
            name='items_left',
            field=models.ManyToManyField(blank=True, related_name='inventory_left', to='items.item'),
        ),
    ]
