# Generated by Django 4.2rc1 on 2023-03-25 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0013_item_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bucket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18)),
                ('amount_in', models.DecimalField(decimal_places=2, default=0, max_digits=9)),
                ('item_count', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
