# Generated by Django 4.2rc1 on 2023-03-26 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0014_bucket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='amount_in',
            new_name='price_in',
        ),
        migrations.AlterField(
            model_name='item',
            name='status',
            field=models.CharField(choices=[('pawn', 'Pawn'), ('redeem', 'Redeemed'), ('saleable', 'Saleable'), ('sold', 'Sold'), ('hold', 'Hold'), ('bucket', 'Bucketed'), ('police_hold', 'Police Hold'), ('missing', 'Missing')], max_length=11),
        ),
    ]
