# Generated by Django 4.2rc1 on 2023-03-26 01:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0015_rename_amount_in_bucket_price_in_alter_item_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='bucket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='items.bucket'),
        ),
    ]
