# Generated by Django 4.1.7 on 2023-03-19 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0004_employee_changed_by_historicalemployee_changed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='first_name',
            field=models.CharField(default='John', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='Doe', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='first_name',
            field=models.CharField(default='John', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='last_name',
            field=models.CharField(default='Doe', max_length=20),
            preserve_default=False,
        ),
    ]
