# Generated by Django 4.1.7 on 2023-03-20 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0005_employee_first_name_employee_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='changed_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='historicalemployee',
            name='changed_at',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2023, 3, 20, 1, 34, 57, 550444, tzinfo=datetime.timezone.utc), editable=False),
            preserve_default=False,
        ),
    ]
