# Generated by Django 4.1.7 on 2023-03-06 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='sub_total',
            new_name='subtotal',
        ),
    ]
