# Generated by Django 4.1.7 on 2023-03-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_alter_transaction_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('pawn', 'Pawn'), ('sale', 'Sale'), ('layaway', 'Layaway')], default='sale', max_length=7),
            preserve_default=False,
        ),
    ]
