# Generated by Django 4.1.7 on 2023-03-16 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('buy', 'Buy'), ('pawn', 'Pawn'), ('sale', 'Sale'), ('layaway', 'Layaway'), ('payment', 'Payment'), ('redeem', 'Redeem')], max_length=7),
        ),
    ]
