# Generated by Django 4.2rc1 on 2023-03-23 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drawers', '0004_drawer_store'),
        ('stores', '0002_store_balance'),
        ('customers', '0004_alter_customer_state'),
        ('employees', '0006_employee_changed_at_historicalemployee_changed_at'),
        ('transactions', '0006_transaction_employee_transaction_store'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='drawer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='drawers.drawer'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='customers.customer'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='stores.store'),
        ),
    ]
